### ISSUE TITLE
Error while loading Audio.sbc when starting debug

### ISSUE THREAD

**Issue by mexmer** [KeenSoftwareHouse/SpaceEngineers#11]
seems Audio.sbc definition contains sounds, that are not in SE content directory.

for now (as workaround) i have copied from my game folder audio.sbc into Sources\SpaceEngineers\Content\Data\

filesize diffence is roughly 10k

**Comment by OndrejPetrzilka** [comment]
Please see #7 or https://github.com/KeenSoftwareHouse/SpaceEngineers#common-issues and let me know if changing value in global.props or user.props helped

**Comment by mexmer** [comment]
nope, it doesn't help, it's only this file ... if you compare 
Sources\SpaceEngineers\Content\Data\
with
steamapps\SpaceEngineers\Content\Data\

you see audio.sbc is different, rest is same.

if you launch build and debug you can see 3 folders are linked into
Sources\SpaceEngineers\Content\
it's data, particles, effects2, rest is linked to game folder (which i have set in user.props)

i think you have uploaded into repo version of audio.sbc from upcoming release, but without sound files

this is where it fails to load

   <Sound>
      <Id>
        <TypeId>MyObjectBuilder_AudioDefinition</TypeId>
        <SubtypeId>ArcWepPlayRifleImpMetal</SubtypeId>
      </Id>
      <Category>IMP_PLAY</Category>
      <MaxDistance>46.6797371</MaxDistance>
      <Volume>0.487672657</Volume>
      <VolumeVariation>4.424721</VolumeVariation>
      <PitchVariation>108.563423</PitchVariation>
      <Waves>
        <Wave Type="D3">
          <Start>ARC\IMP\ArcWepPlayRifleImpMetal3d01.xwm</Start>
        </Wave>
        <Wave Type="D3">
          <Start>ARC\IMP\ArcWepPlayRifleImpMetal3d02.xwm</Start>
        </Wave>
        <Wave Type="D3">
          <Start>ARC\IMP\ArcWepPlayRifleImpMetal3d03.xwm</Start>
        </Wave>
        <Wave Type="D3">
          <Start>ARC\IMP\ArcWepPlayRifleImpMetal3d04.xwm</Start>
        </Wave>
        <Wave Type="D3">
          <Start>ARC\IMP\ArcWepPlayRifleImpMetal3d05.xwm</Start>
        </Wave>
        <Wave Type="D3">
          <Start>ARC\IMP\ArcWepPlayRifleImpMetal3d06.xwm</Start>
        </Wave>
        <Wave Type="D3">
          <Start>ARC\IMP\ArcWepPlayRifleImpMetal3d07.xwm</Start>
        </Wave>
        <Wave Type="D3">
          <Start>ARC\IMP\ArcWepPlayRifleImpMetal3d08.xwm</Start>
        </Wave>
        <Wave Type="D3">
          <Start>ARC\IMP\ArcWepPlayRifleImpMetal3d09.xwm</Start>
        </Wave>
      </Waves>
    </Sound>

but there are others missing, not just this one.

**Comment by mexmer** [comment]
seems problem is related to VS2015, on VS2013 if i go trough all audio.sbc errors(asserts), game launches.
on VS2015, after i ignore all asserts debug mode just freezes.
