### ISSUE TITLE
First build from tutorial fails

### ISSUE THREAD

**Issue by Geneticus** [KeenSoftwareHouse/SpaceEngineers#12]
![error](https://cloud.githubusercontent.com/assets/12452237/7644397/1dd06428-fa59-11e4-9089-becd7434bfaa.PNG)

**Comment by mexmer** [comment]
RightClick SpaceEngineers project in VS.
Click - Set As Default Project

**Comment by Geneticus** [comment]
Thanks! That should be added to the video.

**Comment by Geneticus** [comment]
I see the problem now.  Look at the last row.
![error](https://cloud.githubusercontent.com/assets/12452237/7644649/f669b5b6-fa5c-11e4-9e18-42ca7be87a01.PNG)

**Comment by mexmer** [comment]
this happens, when you don't have set proper path to game content directory
create user.props in same folder as spacenegineers.sln - don't forget to set correct path inside (bellow is my user.props)

```
<?xml version="1.0" encoding="utf-8"?> 
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <!-- Modify the line below to contain path to SpaceEngineers\Content in Steam directory -->
<ContentPath>c:\ProgramData\SteamLibrary\steamapps\common\SpaceEngineers\Content</ContentPath>
  </PropertyGroup>
  <ItemDefinitionGroup />
  <ItemGroup />
</Project>

**Comment by Geneticus** [comment]
Path was set properly. I had VS open and loaded the solution from the File Menu. Launching it from the sln file directly allowed the missing project to load.

**Comment by mexmer** [comment]
you don't need to reload whole solution, just righclick project and select "reload project" ... anyway, good you figured it out

**Comment by Geneticus** [comment]
I didn't have any controls in the context menu for the project. Now to fix all of the Symbol load failures in the projects build options :(
