### ISSUE TITLE
Request: Add ability to load Server Side Modifications and Addons (scripts only).

### ISSUE THREAD

**Issue by sjsoft2015** [KeenSoftwareHouse/SpaceEngineers#157]
Hello. I have an idea. It should be added to the game the ability to load additional assembly by key -addon "foldername or filename".
From this assembly I would like to be able to call methods like switchthruster(). When i'm using plugin system by sesextender, it fails to call these methods. There is a memory error, or the method is performed without producing the effect in game. I try to make a trip jetpack in time. Ie use no more than 3 seconds.

And most importantly, it must be closed code. That it could not be used on another server without permission.

p.s. I could try to do it myself, but apparently do not understand the concept. i just try it by loading assembly directly.

**Comment by sjsoft2015** [comment]
I found something key -plugin in public static void RegisterFromArgs(string[] args);
Interested...

**Comment by THDigi** [comment]
I thought it was already possible since Space Engineers Server Extender is a thing.

**Comment by sjsoft2015** [comment]
Well. It does not work as it should.

**Comment by sjsoft2015** [comment]
-plugin not working...

It seems it was conceived, but not implemented. Let's start with the fact that at the time of loading of my assembly has not initialize MyLog.Default. Besides, I did not find not a single call to this library later ..

**Comment by Tyrsis** [comment]
You need to implement IPlugin.  After that you can check if MyAPIGateway is valid and make calls like that.  It's not really difficult and works just fine.  But what you're asking for is already implemented.

**Comment by sjsoft2015** [comment]
Tyrsis, pls try this. https://docs.google.com/file/d/0B1TzQZ64O1alc2VYYmh4U1d4dXM/edit

**Comment by Tyrsis** [comment]
I don't even have to run it to know this won't work.  You need to understand that plugins get loaded on game load, not when a map is loaded.  You could even modify menus if you want using plugins.  You need to detect when a world is loaded and also check if MyAPIGateway is valid before using it (check to see if MyAPIGateway.Session is null, do not use it until it's not null!)

**Comment by sjsoft2015** [comment]
Check code and you will understand what error is caused in other moments. And it is not connected with the fact of what you write. Try the way uncomment following lines by one at once:
                             //pl.SwitchThrusts ();
                             //pl.EnableJetpack(false, false, true, false);
The link below is a working example for the workshop.
https://docs.google.com/file/d/0B1TzQZ64O1ala0NRVGYzS0I3TGs/edit

**Comment by sjsoft2015** [comment]
Good news everyone!!!
I found a place where game lost argument "-plugin" after start configurator.
Server restart with default arguments at this line:
  ConfigForm.cs:71: Process.Start(MyPerServerSettings.GameDSName + ".exe", "-console -ignorelastsession");
And now i trying to do  patch to correct this. And then i can use a plugin switch to start the server with my own assembly. =)

**Comment by sjsoft2015** [comment]
I'm having trouble with the addition of new instances. They add both services through the utility. By the way, the name of the instance does not contain the keyword associating them with the game. And I can not fix it. But I was able to make a patch. "BugFix for MyPlugin #186"

**Comment by midspace** [comment]
Adding plugins through the command line is adhoc at best.
IMO, It should be done through configuration. Only then will services work.

**Comment by sjsoft2015** [comment]
I think it is, or should developers do?

**Comment by midspace** [comment]
Expanding on what I said above.
When you look at the UI for the SpaceEngineersDedicated, there is a text box for Mods.
Plugins could be implemented in the same fashion. It's just a list of assemblies (.dll files).
The Dedicated Server Configurator will then need to save it into MyConfigDedicated. When the service or host is started, it can then read its own configuration and load up the plugins.
The difficulty I see is, plugins are loaded up first, way before the MyConfigDedicated is read in by the Dedicated server. see the MySandboxGame constructor. ParseArgs(commandlineArgs), and MySandboxGame.ConfigDedicated.Load().
Loading up of plugins cannot be delayed, as some may need to be loaded before other major Space Engineers Types. The alternative is to load up the Config earlier. It is just configuration data at this point.
Does @Tyrsis have an opinion on this?

**Comment by sjsoft2015** [comment]
I checked my plugin for SESE and checked it by the VRAGE with -plugin. The result is the same. So all my words about SESE can ignore. What is really worth asking:
Why is this code ( "https://github.com/sjsoft2015/MyPlugin". sese plugin) does not work as well as this ( "https://github.com/sjsoft2015/SSAPISESEP". mod for workshop, u can use it localy) one.
Perhaps this is due to the fact that the first code is executed on the server side and the client side of the second? And how to synchronize actions from the server to client?

**Comment by sjsoft2015** [comment]
Patch merged #234
