### ISSUE TITLE
Access to API documentation project

### ISSUE THREAD

**Issue by mexmer** [KeenSoftwareHouse/SpaceEngineers#183]
Since CHM file look, like it's made in sandcastle, it would help, if we have access to this project files, and can modify them.

Adding interface docummenation trough 

```
///<sumary>
///
///</sumary>
```

is quite limited, especially when documenting namespace itself.

**Comment by midspace** [comment]
Not sure if this is a duplication of #41. The other was kind of vague.

**Comment by Sibz** [comment]
I think #41 was meaning that we add in all the information into the code to it comes out in the .chm file.
Mexmer is referring to the sandcastle project files so we can further customise the content of the .chm file.

**Comment by mexmer** [comment]
@midspace to me #41 looks like request for internal documentation.

What i'm asking for is documentation source for ModAPI and such (one you find in Tools folder).
CHM looks like it's created using sandcastle from visual studio generated XML that is compiled upon project/solution build from <summary> tags.
That way we will be able to add more information to CHM file, for people who don't want to guess or go trough sourcecode ;o)
