### ISSUE TITLE
Add CurrentPosition to Sandbox.ModAPI.Ingame.IMyPistonBase

### ISSUE THREAD

**Issue by midspace** [KeenSoftwareHouse/SpaceEngineers#2]
Add the readonly property CurrentPosition
to Sandbox.ModAPI.Ingame.IMyPistonBase

**Comment by midspace** [comment]
Update from Keen has completed this.

**Comment by lord-devious** [comment]
Actually, that was my work :smile:

**Comment by midspace** [comment]
:satisfied:
:100: :thumbsup:
