### ISSUE TITLE
[Bug] IMyDoor.OpenRatio:Returns value higher than 1

### ISSUE THREAD

**Issue by Sibz** [KeenSoftwareHouse/SpaceEngineers#204]
Tested on standard door, returns 1.2

Introduced with the feature in
2073ef1743fca874b9ac748c0ee07677e151b208

**Comment by mexmer** [comment]
in that merge value was only populated to interface, therefore computation must have been wrong already before that field introduction.

**Comment by lord-devious** [comment]
I can confirm this, the value returned is actually not a ratio, it's in meters - I remember the value. I'm suspecting, but not certain, that this is a remnant of a partial merge of a PR I originally created in the old repo, where this property was named DoorPosition and indeed returned the offset in meters. @OndrejPetrzilka wasn't quite happy with another part of this feature, where I made it possible to disable opening and closing of doors by their control panel, so he only merged parts of it. Perhaps there was a misunderstanding, and he renamed it to DoorRatio?

**Comment by Sibz** [comment]
Tested a hangar door: It returns 1 when fully open. I'll take a look at the code when I get a chance.

**Comment by lord-devious** [comment]
Yes that is correct, the hangar door actually uses a ratio. In my old PR I recalculated that into meters.
