### ISSUE TITLE
Checkbox actions similar to On/Off button

### ISSUE THREAD

**Issue by mexmer** [KeenSoftwareHouse/SpaceEngineers#208]
well, idea behind this is to have _Check and _Uncheck action, like we have _On and _Off

there might be situations, where you just want to turn something off (uncheck), or on, and just don't want to bother about state.

like for example script that will turn off broadcasting on all antenas, or lets say enable check for humans on all sensors, and so on

concept of this can be found here
https://github.com/mexmer/SpaceEngineers/tree/terminalproperty-checkbox-actions

i did this i byproduct of another thing i was working on, and want to know, if it's even desired, or if you think it should be done different way.

please note, enabling check/uncheck actions also add this as toolbar action, which might not be desired (too long actions menu on blocks)
see http://i.imgur.com/Xg9rzEu.jpg

also note, only block (as example) where this is enabled is antena.
you can easilly do this for any block just add .EnableToggleActions(); after any .EnableAction() on checkbox construction.

pros
- you can have 2 buttons, one for off, one for on
- you can force on/off action regardless current state (eg. no need for state check)

cons
- it's redundant (at least from pb point of view), since we have setvalue/getvalue (see #207, which is also integrated in branch mentioned above)

**Comment by lord-devious** [comment]
I don't think there should be enable/disable actions, it feels redundant. Your #207 is a far superior way to do this, standing alone. IMO _all_ terminal controls should derive from that value base class and have a representative terminal property. Much better than actions.

**Comment by lord-devious** [comment]
One thing though, I think it would be a good idea to use the same suffixes as the OnOff action does. It is also used for doors (Open_On, Open_Off) so the checkboxes should use *_On and *_Off rather than *_Check and *_Uncheck. The fact that they are checkboxes in the UI is really irrelevant.

**Comment by mexmer** [comment]
@lord-devious good point about On/Off and Check/Uncheck ... was not sure about it myself, then i gone with logical name ... since it's checkbox it's check uncheck, tho' it effectively turns something or on off

as for redudancy, there are 2 points of view.
i'm not sure, if it can be done way that for toolbar it will add on/off action, but not for PB .... terminalproperty seems little mysterious to me ;o)

**Comment by lord-devious** [comment]
I think my current conclusion is that once you standardize the suffixes to what already exists this is a good addition.

**Comment by mexmer** [comment]
@lord-devious done

**Comment by mexmer** [comment]
i've added onoff to few checkboxes (that i think people might want to have on button panels). removed imo unneccesary show shipname.

one thing about button panels is, that unlike toolbars, you don't see toggle status on button panel.

**Comment by mexmer** [comment]
i'm closing this issue, since there is PR pending ... no need for redundancy.
