### ISSUE TITLE
Possible issue with the EULA

### ISSUE THREAD

**Issue by CliffracerX** [KeenSoftwareHouse/SpaceEngineers#217]
The EULA states that the source code is only to be used for modding Space Engineers, and yet it has also been said by Keen that they will help people to make their own standalone games using the VRage engine, which would be in violation of the EULA as a standalone game is not a mod.

Am I missing something here?

**Comment by mexmer** [comment]
i think, you missing that you are in SE sourcecode.

Vrage for other uses will be released separatedly IMO

**Comment by CliffracerX** [comment]
I'm very much looking forward to seeing VRage as a separate engine, I would love to dabble around in development with it.

**Comment by Phoenix84** [comment]
Keen did state that large extensions (such as total conversion) could be put on Steam as a separate game (or item maybe?). I'm not sure if they stated what that would be, but I took it as an expanded mod of SE, something not possible with the workshop.

**Comment by CliffracerX** [comment]
There was nothing about that in the EULA, which probably means in order to get access to the VRage engine for doing that, you need to actually ask them for the VRage engine.

**Comment by harag-on-steam** [comment]
This is a non-issue. There's nothing to stop Keen from licensing their technology under a different, additional set of terms.

**Comment by midspace** [comment]
There is nothing to stop a prospective developer from licensing the VRage engine separately.
I went through the same process in using portions of the MinerWars code from GitHub in the SEToolbox. EULA conditions specifically state it cannot be used in that way, which is why I made arrangements directly with KeenSWH.

It's a non issue. Can we please close this.

**Comment by CliffracerX** [comment]
At the behest of people, closing.  Sounds like it was a non issue afterall.
