### ISSUE TITLE
How to sync a pull request?

### ISSUE THREAD

**Issue by IhanaMies** [KeenSoftwareHouse/SpaceEngineers#218]
I want to sync my pull request with KeenSoftwareHouse/master, how do I do it?

**Comment by THDigi** [comment]
The PR's content is taken from your branch, update your branch and it'll update the PR.

**Comment by IhanaMies** [comment]
My master branch is updated, but the branch I did the PR is not and I need help with it.

**Comment by THDigi** [comment]
Ah, in that case, checkout your branch and then do a rebase using `git rebase master`.

You might get conflicts which you'll have to solve manually, instructions will be on screen if that's needed.

**Comment by Phoenix84** [comment]
I guess there's a lot of ways to do it. I hate git.
I do git pull KeenSoftwareHouse master
