### ISSUE TITLE
Add modifiable flag for indestructible blocks.

### ISSUE THREAD

**Issue by devu** [KeenSoftwareHouse/SpaceEngineers#22]
As per title, to have blocks managed by admin without workarounds that never works and fully protects against destruction.

**Comment by sjsoft2015** [comment]
bad idea.
it would be better to make the admin area. where you can prevent the destruction of objects and even weapons. that it has not worked.

**Comment by devu** [comment]
Well, safe zone is completely different subject. Why individual blocks are bad idea? Imagine I would like to make neutral base for my players to enter, to use some trade terminals. And I can't because right click with drill will ruin whole idea. And I would say preventing with workaround op components and all that crazy stuff is a bad idea. 

Adding simple routine for omitting blocks with that flag would exclude them from damage calculations.

**Comment by sjsoft2015** [comment]
Because I can come to you at the base, connect the terminal and my engines and fly to the object does not break. Are you going to put that flag for a number of cubes? create a copy of all objects in the game with a flag indestructible? Or do you just need to nobody on your base could not destroy it or take control?
In this case, the area has a meaning. Even if someone will manage to knock out base from a place outside of area, it will be the usual stuff.

**Comment by devu** [comment]
No, what I mean is simply to have a property in the class of the cube block
that when set to false, can take no damage. Same as turning block on or off
will disable it on grid.
How is it going to be manageable is a different story. It could be done as
well as by admin area you talking about, can be a shield that will take
damage and when its energy is exhausted will set flag back to destructible
cubes etc.

It doesn't need to be a static config, no copy of definitions at all just
adding 1 property and routine into the code that calculates damage.

**Comment by sjsoft2015** [comment]
Let's see what others will say.

**Comment by zrisher** [comment]
I think this is needed, there's definitely a desire in the server admin community to have indestructible blocks they can place but no one else can. Currently this is done (as devu said) by just making those blocks take an insane amount of components. But that doesn't perfectly protect from damage and is a pretty nasty workaround when you have objects with ridiculous mass flying around with ridiculous thrust output and power generation just so they can be indestructible.

**Comment by demolish50** [comment]
They need to be indestructible and immobile.

**Comment by devu** [comment]
Today's update made my very happy. Changed some random grid flag to 
<DestructibleBlocks>false</DestructibleBlocks>
And works on multi despite a statement it is only for scenario worlds. I did so on standard Survival one. If that wasn't your intention Keen please do not change it, we are very happy about that :)

And per grid solution is good enough for most of our cases.

Now new addition comes to my mind. Not being able to build on such grid because even admin will have trouble to remove random unwanted addition to indestructible blocks at current state. ;)

Thank you Keen for today's update!
