### ISSUE TITLE
[Bug] Programmable Block no longer outputs exception

### ISSUE THREAD

**Issue by Sibz** [KeenSoftwareHouse/SpaceEngineers#237]
No longer getting exceptions output:
```c#
Main(string argument)
{
throw new Exception("This does not get output into detailed info");
}
```
@lord-devious Hoping you can help with this one.

**Comment by lord-devious** [comment]
Since this is possibly my fault, obviously I'll take a look at it. I could have sworn I explicitly tested this but apparently not.

**Comment by Sibz** [comment]
@lord-devious Thank you :-) Your additions are absolutely wonderful!

**Comment by lord-devious** [comment]
I wish I could do this before the hotfix release tonight, but that's impossible.

**Comment by lord-devious** [comment]
Good news! I made contact with Keen to ask if there was a chance to get this fix into the hotfix tonight, turns out they've already fixed it internally.

**Comment by Sibz** [comment]
:+1:

**Comment by Sibz** [comment]
Confirmed Resolved in latest build
