### ISSUE TITLE
Replacing On/Off switching with checkboxes

### ISSUE THREAD

**Issue by mexmer** [KeenSoftwareHouse/SpaceEngineers#240]
reasons
terminal UI starting to be cluttered and unreadable

pros
- use less space 
- look more natural in many cases
- use less space

cons
- some texts will need to be shortened, which migh be problem in some languages, or if we stick with "long" text, there will be no benefit

question is, which on/off buttons should be replaced, and which should stay.

for those, that should stay
Block Enabled - On/Off - i don't feel checkbox is appropriate for this

for those that should be changed
Show in terminal
Show in toolbar

add more, or discuss, why it should stay as is

**Comment by No-Brain** [comment]
If anything I would do it the other way around

**Comment by mexmer** [comment]
@No-Brain you mean replace all checkboxes with on/off ?

that will make a big mess in ui
unless you redesign On/Off to something more compact

or i don't understand what you mean ... care to explain?

**Comment by andrew-w** [comment]
I agree that in some (not all cases) a checkbox is cleaner and looks more correct.  In fact, I would've used one when I added the the "Show in toolbar" option, but I was just keeping things in line with Keen's existing UI.

**Comment by Eikester** [comment]
in some cases a single button (Toggle Button) would be enough and better than a checkbox i.e. On/Off or Open/Close -> make it only one Button that just toggles the current state

**Comment by mexmer** [comment]
that's one thing i thought about also. will need to do some graphic tho'

i was thinking about something similar to this
http://www.freebiewebresources.com/wp-content/uploads/2013/06/On-Off-Switches-and-Toggles.png

of course in style of SE gui

**Comment by Mrjinx453** [comment]
+1 - I would love to see something more clear for the toggle hide the amount of times since they added it i've gone to turn something off and hide it instead is... well alot.
a tick box for the other options, and the same "power on/off" would keep things the same but different to help!. also there are a few blocks that could do with on-off function that dont currently have it.

**Comment by joemorin73** [comment]
@mexmer I like the idea of the slider.  But to do this, don't we need access to the content resources?

**Comment by kittle31** [comment]
Better option is to keep the current visual appearance of <On / Off>  but change the functionality to "set" instead of "toggle"   so when I click on 'on' and the block is already on, it stays on.  Same for 'off'

**Comment by zrisher** [comment]
:+1: to kittle's idea anywhere the current sliders end up remaining. Clicking "On" and having it toggle "Off" is super confusing.

**Comment by mexmer** [comment]
@kittle31 seems you missed whole point of this. 
it's have more compact and more consitent UI

**Comment by kittle31** [comment]
@mexmer I think we mis-understood each other.  in some cases it makes sense to have a checkbox like you said in the OP, but in other cases it does not.

For the places where On/Off does make sense -- namely block states,  We need to have clicking on the On/Off actually make sense.
