### ISSUE TITLE
DX11 multi monitor setup - wrong MyAdapterInfo Handling

### ISSUE THREAD

**Issue by planetenkiller** [KeenSoftwareHouse/SpaceEngineers#253]
The DX11 Render does not handle multiple outputs (monitors) correctly.

The problematic loop (MyRender11.CreateAdaptersList(), for(... `adapter.Outputs` ...)):
https://github.com/KeenSoftwareHouse/SpaceEngineers/blob/master/Sources/VRage.Render11/Render/MyRender-Adapters.cs#L233
The loop overwrites the `info` object instead of creating new `MyAdapterInfo` instances.

**Comment by mexmer** [comment]
looks like that might be it.
when i was doing fix for memory check, adapters were added to list in Output cycle (3 days ago github version)

**Comment by planetenkiller** [comment]
fixed in master branch
