### ISSUE TITLE
[Bug] Damage taken when opening doors inside a pressurised environment.

### ISSUE THREAD

**Issue by Sibz** [KeenSoftwareHouse/SpaceEngineers#265]
Steps to reproduce:
Need two generally large rooms with a door in between.
Close door when rooms not pressurised.
Pressurise both rooms.
Open door.
For a split second the rooms become 0 oxygen.

I have been looking in to this today, and from what I understand this is what is happening:
When you close the door when the room is not pressurised, the Big room, lets call it room A, becomes two smaller rooms, lets call them room B and C. 
When this happens, room A still exists with no pressure.
Then you pressurise room B and C. Room A is still at no pressure, but B and C have pressure.
Then when you open the door, rooms B and C become room A again, room A still has no pressure unlike the rooms B and C. Next its calculates room A's pressure from the old values of room B and C and restores the pressure to what it should be.

private bool PressurizeProcessQueue(int count) Is called which 'swaps' in Room A / Rooms B&C
private void PressurizePostProcess() is then called which recalculates the pressure.

The issue happens because the Pressurize process is split up to prevent the process from hogging cpu time, this allows updates in between, hence the character updates, see's there is no oxygen and takes damage.

At least this is my theory, and I am opening the issue to bring it up for discussion. I could be completely wrong. But I am hoping by opening an issue we can get to the bottom of this.

**Comment by Spartan322** [comment]
If the cause of this bug is what you say, probably a better way to deal with that would be to check the pressurization of all rooms incorporated inside a metaroom with an AND compare operator and replace the metaroom value with that result, and the metaroom's pressure of course should be:
```C#
float oxy_value = 0;
foreach(Room r : GetAllRooms()) {
 value+=r.GetOxygenValue();
}
value /= GetAllRooms().Length;
```
value would be the average result (this action would be optimally calculated right before something like a door opening)
