### ISSUE TITLE
Oxygen use from within vacuums

### ISSUE THREAD

**Issue by EveColonyCommander** [KeenSoftwareHouse/SpaceEngineers#281]
Scenario: Player enters a sealed and depressurized ship. Ship flies into pressurized hanger. Player now can remove helmet without leaving the depressurized ship.

Players appears to ignore sealed environments when attempting to find breathable air and will use external resources when the immediate room is a vacuum.

**Comment by mexmer** [comment]
first, don't understand what you trying to say.
second, for suggestions use forum, github forum is for discussing code issues and interface changes, not to discuss player sugestions

**Comment by MeusRex** [comment]
I think he wants to say that there is a bug. That you can remove your helmet inside a ship without an atmosphere if the whole ship is inside a room with atmosphere.

**Comment by EveColonyCommander** [comment]
MeusRex is correct. While within a unpressurized(but sealed) ship you can breathe if the ship is within a oxygenated location(such as a hanger). I do not see this as a bug so much as an oversight due to a simple first implementation.

**Comment by mexmer** [comment]
but this is not bug, you can remove helmet anytime, even in open space. it will just kill you after some time, if you do that.

as for breathing, did you wait at least 2 sec?
player damage for airless environment is counted either on interaction, or after 100 frame updates (with 60ups - it's around 1.8 sec)

**Comment by mexmer** [comment]
Still, if you have bug report, post it on forums. Here it might lie unnaddressed many weeks.
On forums, any bug submitted gets tested by KSW tester, and apointed ticket in their internal tracking system.

Unless you are pointing out bug in someones PR, then forum is best way to submit bug.

Github issue tracker is not forum replacement.

**Comment by EveColonyCommander** [comment]
"But this is not bug, you can..."

To clarify: You can survive in an airless ship if that ship is inside another ship which has air while your helm is removed.

To recreate: Build large ship w/ air system. Build second ship inside the first w/o air system(second ship must be air tight). Enter second ship and remove helm.

Result: Engineer uses first ship's air system to breathe, ignoring the second ship's lack of air. So long as the second ship remains within the first ship the engineer does not need a helm

-----
"Still if you have bug report..."

I understand that now. I will see about moving the information on this bug to the forums.

**Comment by mexmer** [comment]
so, if i understand correctly, you receive no damage in "sealed" airless area, that is inside area that is filled with air ... that indeed sounds like a bug.

still my point about using forums for bug report stands ... if you check PRs and issues here, some were not addressed almost since start of going opensource ... while on forums you get at least note from Phand, that ticket has been created, and updates ....

**Comment by EveColonyCommander** [comment]
Yes, that is what I mean. 

Thank you for the information. In the future I will attempt to address issues with greater clarity and to the correct sources(such as the forum). Should I close this issue then since it is unlikely to be seen?

**Comment by mexmer** [comment]
yes i think, you can close it here, after you repost it on forums.
I believe it will be reviewed on monday by phand or other tester, and reported to devs.
