### ISSUE TITLE
Storage Prioritization 

### ISSUE THREAD

**Issue by cyber01** [KeenSoftwareHouse/SpaceEngineers#330]
Hello, is it possible to add to the game prioritization storage? For example, we have a storage with the highest priority and all resources should default to take shape, if it is not available / filled in another location, lower priority. And so in this conveyor system by default it adds all the storage with the highest priority.

I think it would be useful if there is a plurality of storage or a large database.

P.S. Is it possible to do the sorting means of the conveyor system, and Sorter is not (or at least make it a bidirectional (input and output from the storage / device))

Sorry for my bad English

Thanks

**Comment by devu** [comment]
It would be great solution to the sorting problem without introducing
sorter block that kills multiplayer performance.
+1

**Comment by cyber01** [comment]
What about prioritization?

**Comment by joemorin73** [comment]
Can this not be done with Programming Block scripts?

**Comment by cyber01** [comment]
I dont know, i dont have programming skills.

**Comment by joemorin73** [comment]
If you look in the workshop, there have been some submissions to manage inventory.  I recommend check a few to see if one works for you.

**Comment by cyber01** [comment]
Ok, thanks.

Anything example?

**Comment by joemorin73** [comment]
Unfortunately, no.  I tend to custom write my own.  I'd try sorting by what's popular.  It'll be a trial and error.
