### ISSUE TITLE
What's the location of the quotes in the game files?

### ISSUE THREAD

**Issue by aaronfranke** [KeenSoftwareHouse/SpaceEngineers#350]
What's the location of the quotes in the game files?

**Comment by FavioGalvis** [comment]
![giphy](https://cloud.githubusercontent.com/assets/12051180/8710720/85c767d2-2b11-11e5-8b33-c85c673358e0.gif)

**Comment by aaronfranke** [comment]
The ones that you see when the game loads.

**Comment by wardmatt1** [comment]
..\SpaceEngineers\Content\Data\Localization
they are in the various language files, not part of the source code.

**Comment by aaronfranke** [comment]
Thanks!
