### ISSUE TITLE
VS 2015 compatibility

### ISSUE THREAD

**Issue by midspace** [KeenSoftwareHouse/SpaceEngineers#371]
Under Visual Studio 2015, the TextTransform is v14.0.
C:\Program Files (x86)\Common Files\Microsoft Shared\TextTemplating\14.0\TextTransform.exe

Under Visual Studio 2013, the TextTransform is v12.0.

This matches the internal versions as published in Wikipedia.
https://en.wikipedia.org/wiki/Microsoft_Visual_Studio

After making the appropriate changes to the SpaceEngineers/3rd/Utils/RunTemplate.bat
The solution compiles and runs without any issues under VS 2015 community edition.

**Comment by OndrejPetrzilka** [comment]
Should be fixed with ad0593c..3da3e3e, please test it

**Comment by midspace** [comment]
It's working perfect.
