### ISSUE TITLE
3rd party asemblies was not updated, is preventing the source from compiling.

### ISSUE THREAD

**Issue by leftler** [KeenSoftwareHouse/SpaceEngineers#424]
When @LeonidasCZ did the commit 1c4032eebb9c277ed759e8d2c34d90c291d918e7 today the [SpaceEngineers/3rd](https://github.com/KeenSoftwareHouse/SpaceEngineers/tree/master/3rd) folder was not updated.

This is causing the error
```
'BitStream' is an ambiguous reference between 'VRage.Library.Collections.BitStream' and 'VRage.Network.BitStream'
```
throughout the VRage.Network project due to both it and `RakNet` both defining a `BitStream` type (VRage.Network.BitStream is a type defined in the RakNet assembly).

**Comment by t3hk0d3** [comment]
+1

**Comment by Geneticus** [comment]
Meh. I was just about to start integrating my hardware with vrage :(

**Comment by amahlaka** [comment]
any update on this?

**Comment by t3hk0d3** [comment]
@amahlaka Looks like they won't fix repository until Planetes release.

**Comment by leftler** [comment]
The latest commit fixes the compile problems
