### ISSUE TITLE
Only one LCD/text panel renders at a time

### ISSUE THREAD

**Issue by cwc** [KeenSoftwareHouse/SpaceEngineers#43]
Reproduce by placing multiple panels that are set to display text, close enough to each other that you can see both of them. Turn so that only one LCD is in view. When turning back to view both LCDs, the other will read OFFLINE. Affects singleplayer as well as multiplayer.

This one's been bugging me for awhile, so I looked into it. The [GetRenderTexture](https://github.com/KeenSoftwareHouse/SpaceEngineers/blob/master/Sources/VRage.Render/MyRenderTexturePool.cs#L24) method is responsible for returning the texture to which the text is rendered. The method successfully returns one texture, but subsequent calls fail and return null, due to the [`m_currentFreeResources >= textureResourceSize`](https://github.com/KeenSoftwareHouse/SpaceEngineers/blob/master/Sources/VRage.Render/MyRenderTexturePool.cs#L29) check failing. The [initial value for free resources](https://github.com/KeenSoftwareHouse/SpaceEngineers/blob/master/Sources/VRage.Render/MyRenderTexturePool.cs#L17) doesn't seem very large to me. If I just change it, multiplying it by N, I'm capable of rendering N text panels at a time, with no apparent problems.

I think the resource limit should be set dynamically, somewhere. I'm not really sure where that should happen or what the calculation should look like.

**Comment by MMaster** [comment]
I did not study the code, but did you also find out why turning off Render Interpolation and lowering graphics quality solves this issue?

**Comment by lord-devious** [comment]
What is interesting is, that at least for me, reloading the world fixes the problem.

**Comment by cwc** [comment]
@MMaster I'm pretty sure lowering the graphics quality changes the [quality scale value](https://github.com/KeenSoftwareHouse/SpaceEngineers/blob/master/Sources/VRage.Render/MyRenderTexturePool.cs#L26), therefore the math will allow more textures for LCDs.

@lord-devious I have seen on occasion all LCDs come online when the world initially loads, but it quickly goes back to the buggy behavior when I start moving around. I can upload the world file to Steam if you, or anyone else, would like to take a look.

**Comment by mexmer** [comment]
disabling interpolation solves issue only temporary, after some minutes it goes back to bug state. i even posted vid, how it looks. problem is more complex, than just fixing one container.

**Comment by MMaster** [comment]
@mexmer when I disable interpolation and set quality to high it never happens to me. It only happens when I use extreme quality setting.

**Comment by mexmer** [comment]
i use high quality, and happens always.

**Comment by cwc** [comment]
So the count of free resources available to render LCD panels is initialized according to normal rendering quality when the game is started. Once the user's settings are read and the rendering quality is set to a higher level, the count of free resources is not updated until the renderer unloads content and frees resources - which happens when you exit a game world. This explains why the symptoms can be worked around by reloading a game/reconnecting to a server, and why those using normal quality settings don't have the problem.
