### ISSUE TITLE
G-Menu - "All Blocks" group is missing some items

### ISSUE THREAD

**Issue by ChrisonSimtian** [KeenSoftwareHouse/SpaceEngineers#430]
Some blocks seem to be missing since the latest patch if you go to "All blocks"
I have only recognized that for oxygen blocks so far, but it might be some more
(dont know all of them by hearth, but I'll keep this issue up to date if I recognize more missing blocks)

Game Setting:
- Fresh world (first one after the latest patch)
- Started in Survival
  --> then edited settings to Creative (where I found this issue)

Not sure yet whether this was caused by switching from Survival to Creative or if it already happened to the survival game.

**Comment by mexmer** [comment]
this can happen, if you have large number of blocks. grid has limited number of entries it will display (can't remember exact value)

**Comment by ChrisonSimtian** [comment]
thats weird... it happened in a world without any mods, so I'd expect SE to show all blocks.
Also it DID display all of them before the last patch, so something changed in between and made some blocks disappear

**Comment by mexmer** [comment]
guess, you can close it here.
after reading some comment on forums bug section, seem it's bug related to dynamic block grid resize.  behavior i described here was prepatch (1.101 and older probly), current version behaves different way.
