### ISSUE TITLE
Increased dedicated CPU usage after 22nd October patch

### ISSUE THREAD

**Issue by massl** [KeenSoftwareHouse/SpaceEngineers#442]
After yesterday's patch I've noticed a huge increase of idle CPU usage for dedicated servers.

I could very simply verify it by starting a new world dedicated server via the regular launcher. On my PC the CPU usage without any active player was up to 20%(!).

The cpu usage for empty servers should ne near zero. Other games achieve this my reducing the simluation rate dynamically, but this looks like another issue that raised up with the last patch.

**Comment by IhanaMies** [comment]
This belongs to the forums. Not here

**Comment by massl** [comment]
Aye. Luckily it has been fixed on the same day (big up Ondrej).
