### ISSUE TITLE
Unable to run game from latest source code

### ISSUE THREAD

**Issue by cole-ifthisusernameistakenimgoingtocry** [KeenSoftwareHouse/SpaceEngineers#454]
when trying to run the project in debug mode, it crashes due to an unhandled exception in MyRender-Device.cs. Here is the error message: 

An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll

Additional information: HRESULT: [0x887A002D], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: The application requested an operation that depends on an SDK component that is missing or mismatched.

I have already updated global.props, and even tried redownloading the source code but it still fails with the same error.

**Comment by leftler** [comment]
I ran in to this too, if you run in DX9 mode it will work.

**Comment by cole-ifthisusernameistakenimgoingtocry** [comment]
Running the game in dx9 mode seems to have fixed the issue
