### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by jramador66** [KeenSoftwareHouse/SpaceEngineers#455]
Trying to get my planets to work,you think you can help me out??

**Comment by Pingger** [comment]
Not with that few information ...
What the community will need:
1. The Problem
2. if it's a game crash: At which point does it crash?
3. Are you playing in Singleplayer or Multiplayer?
4. Are Mods installed?
5. The LogFile (located at %AppData%\SpaceEngineers\SpaceEngineers.log)

**Comment by Spartan322** [comment]
In all cases, this should be on the forum, not here. This is for code contributions and issues.
