### ISSUE TITLE
Recharging and Discharging is not exposed to for Sandbox.ModAPI.Ingame.IMyBatteryBlock

### ISSUE THREAD

**Issue by maragnus** [KeenSoftwareHouse/SpaceEngineers#458]
There is no way in the in-game scripts to determine whether Discharge, Recharge or Semi-auto are checked.  Also, the source does not appear to be up-to-date enough to have the Discharge option in the code.

**Comment by mexmer** [comment]
wrong, there is a way, all chekboxes state (true/false) can be evaluated in pb.

**Comment by maragnus** [comment]
Thanks. You are correct, I will close.  It would appear it's also well known the code is out of date, regarding missing discharge.
