### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by laftur** [KeenSoftwareHouse/SpaceEngineers#460]
"A first chance exception of type 'System.InvalidCastException' occurred in Sandbox.Game.dll"

1) git clone
2) open the solution in msvs2013
3) start debugging
4) An exception starts on line 58 of MyConfigBase.cs and goes unhandled. The game doesn't even start.

**Comment by peltco** [comment]
The problem is that in your SpaceEngineers.cfg the DebugInputs section is something like this

    <item>
      <Key xsi:type="xsd:string">DebugInputs</Key>
      <Value xsi:type="SerializableDictionaryOfStringMyDebugInputData">
        <dictionary />
      </Value>
    </item>

And MyDebugInputData is not known in the sourcecode.

you can change it to this

    <item>
      <Key xsi:type="xsd:string">DebugInputs</Key>
      <Value xsi:type="SerializableDictionaryOfStringObject">
        <dictionary />
      </Value>
    </item>

and your game will start.

(Note that the latests version is 1.112 and this source is 1.103 probally explaining the difference)

**Comment by laftur** [comment]
Thanks for your response! The change you suggested caused the exception to be avoided.

Sorry for my lack of understanding of the configuration files, but does the steam distribution of the game require that value to be "SerializableDictionaryOfStringMyDebugInputData"? I'm wondering why the default isn't "SerializableDictionaryOfStringObject" to begin with.

Alternatively, as I assume there is purpose behind the former value, may I suggest this information be included as part of the quickstart section of the readme?

**Comment by peltco** [comment]
The reason is that keen introduced a MyDebugInputData type somewhere between the current github sources and the current life sources. We just don't know what MyDebugInputData looks like and we'll have to wait till they merge their code.
