### ISSUE TITLE
Air Vents don't take into account external atmospheric conditions

### ISSUE THREAD

**Issue by lostkangaroo** [KeenSoftwareHouse/SpaceEngineers#469]
As far as I have been able to track down this reasoning, it seems that air vents are still tied to the assumption they would only be used to pressurize sealed internal rooms.  This assumption should be changed due to planets introducing another type of environment, the planets atmosphere.  Air vents should now report the value for the environment the grid they are attached to is surrounded by when an oxygenBlock.Room is missing; 0 for space naturally or the planet/moon/celestial body's atmospheric default.

**Comment by mccorkle** [comment]
Hey Lost -- This issue tracker is for discuss source code contributions, not making bug reports.  There is a dedicated thread (http://forum.keenswh.com/forums/bug-reports.326950/) to post bug reports for Keen to see.

**Comment by lostkangaroo** [comment]
This is not a bug report but a feature request as the current functionality does not exist in current assumptions. It can be considered a bug report if the general idea is for this behavior to exist, but that is a Keen decision.

**Comment by nobodyhasthis** [comment]
If it is a feature request. Try putting it in http://forum.keenswh.com/forums/suggestions.313735/

**Comment by lostkangaroo** [comment]
It has been but I have a feeling its been lost to the black hole of page 99+ by this point. My concern is not so much about what keen forum to post this in.  If there is another oxygen system PR or issue that is gaining more traction I would be happy to attach this issue to it rather then pursue this specific feature in this issue.
