### ISSUE TITLE
Fix turret burst fire rate 

### ISSUE THREAD

**Issue by DracheTek** [KeenSoftwareHouse/SpaceEngineers#470]
As I have noticed, the rocket turret and reloadable rocket turret simply follows a "shoot four rounds-reload for two seconds-shoot again" pattern, and the reload interval is not moddable. Since many mods are using rocket turrets as their base, this scheme is heavily restricting the creativity of the community.

I recommend to move the reload (mentioned as burst fire in source code) function to a more basic class, so that every weapon has a moddable choice whether it is fed by magazine, and whether they need reload, and how long it is.

Also posted in the suggestion part of the forum.

**Comment by LeonidasCZ** [comment]
fixed by #481
