### ISSUE TITLE
Cannot Debug. dll files could not be found

### ISSUE THREAD

**Issue by kuroodo** [KeenSoftwareHouse/SpaceEngineers#5]
Just downloaded the files & followed instructions on on github page (same as readme file).

I get errors all telling me that these dlls are missing:
Sanbox.game.dll (located SpaceEngineers-master\Sources\Sandbox.Game\bin\x86\Debug). I checked and there is no such file in there.

The next one is SpaceEngineers.Game.dll (located in the same directory above).
I have tried rebuilding the project but no success.

Error	1	The command "..\..\3rd\Utils\RunTemplate.bat "C:\Users\KuroodoD\Desktop\Programming\SpaceEngineers-master\Sources\Sandbox.Game\Engine\Utils\MyEnumToStringsGenerated"" exited with code 1.	C:\Users\KuroodoD\Desktop\Programming\SpaceEngineers-master\Sources\Sandbox.Game\Sandbox.Game.csproj	1223	5	Sandbox.Game
Error	2	Metadata file 'C:\Users\KuroodoD\Desktop\Programming\SpaceEngineers-master\Sources\Sandbox.Game\bin\x86\Debug\Sandbox.Game.dll' could not be found	C:\Users\KuroodoD\Desktop\Programming\SpaceEngineers-master\Sources\SpaceEngineers.Game\CSC	SpaceEngineers.Game
Error	3	Metadata file 'C:\Users\KuroodoD\Desktop\Programmin\SpaceEngineers-master\Sources\Sandbox.Game\bin\x86\Debug\Sandbox.Game.dll' could not be found	C:\Users\KuroodoD\Desktop\Programming\SpaceEngineers-master\Sources\SpaceEngineers\CSC	SpaceEngineers
Error	4	Metadata file 'C:\Users\KuroodoD\Desktop\Programming\SpaceEngineers-master\Sources\SpaceEngineers.Game\bin\x86\Debug\SpaceEngineers.Game.dll' could not be found	C:\Users\KuroodoD\Desktop\Programming\SpaceEngineers-master\Sources\SpaceEngineers\CSC	SpaceEngineers

**Comment by THDigi** [comment]
It's because of that batch file failed to find TextTemplating.exe, search for the file manually and post the path to it :P
But, are you using VS2013 ? I had the same issue with VS2012, if you're using that you could just make that .bat file blank to ignore it but it's prefered to just upgrade to VS2013.

**Comment by devu** [comment]
VS community edition or full version can only help here because you need
full SDK.

**Comment by kuroodo** [comment]
Okay it started working. I had VS2013, but apparently I didn't. So reinstalled vs2013 and the SDK and now it works.

**Comment by Mix-martes86** [comment]
Indeed it won't work. With Express, it says that neither VS nor its SDK are installed. I reinstalled the thing just to see if I got a bad install. Is there any site where I can get the 4 files contained in that TextTemplating folder? I hate "blank the file" kind of workarounds.

**Comment by mexmer** [comment]
I recommend installing community edition of VS, not only it has more options, but most importantly it allows you to install and use VS plugins (unlike express editions)
