### ISSUE TITLE
Vide Card not supported error

### ISSUE THREAD

**Issue by Morketh** [KeenSoftwareHouse/SpaceEngineers#517]
Alright this is rather annoying after some hours of playing Space Engineers i crash to desktop with a videcard not supported error message. looking at the minimum system requirements, i find that there bottom of the line card is is a GeForce 880 GT and my card is a GeForce GTX 570.
My card isn't all that better then an 8800 but its definitely above an 800 in spec.
http://www.hwcompare.com/9128/geforce-8800-gt-512mb-vs-geforce-gtx-570/

yes ive updated all my drivers changed every setting on the game i could think of re optimized every aspect of my computer in the way of background tasks and drivers to see if there was a conflict. 
end result is always the same Card Not supported and a Crash to desktop. 
any sugestions on how to fix this? Aside from building a 14 thousand dollar system, Im all about throwing more hardware at problems but the last few patches have been hell on everyone with the bouncing and the glitching, and i doubt any amount of hardware in the world could fix these problems

**Comment by nulling** [comment]
14 thousand dollar system?
A decent system should start at 750-ish. Don't know where you got your $14,000 figure from.

**Comment by Morketh** [comment]
Really? You don't know what an exaggeration is?

**Comment by JamesK89** [comment]
I'd like to mention that in my group of friends this has been observed with both AMD and Nvidia GPU's. My hypothesis is the game is doing something that both video drivers don't like causing the driver to crash and so DirectX 11 attempts to recover but during the recovery the driver is still hasn't reloaded so the only device left during these events is possibly the DirectX Reference Device, or perhaps a null device, which Space Engineers doesn't support.

**Comment by Morketh** [comment]
Any ideas on how to solve this?

**Comment by mze9412** [comment]
Read the forums ;) This is just for source code issues, not for generel bugs :dancer: http://forums.keenswh.com/threads/fix-graphics-not-supported-graphics-card-shuts-down-restarts-fix-for-both.7383074/

**Comment by Morketh** [comment]
One of the causes related to this error is unoptimized coding. So I'm
posting it here were the code is so it can be properly optimized. I
shouldn't have to play around in my registry or write additional
applications because software developers are sloppy coders. I'm all for
those finite tweaks to pinch out that extra 2% of quality. But come on I
shouldn't have to do that to make the application useable. It's like buying
a brand new corvette from the dealer and the manufacture expects you to
adjust the timing chain. That sounds like a source code issue to me.

**Comment by mze9412** [comment]
And such things will be ignoried here. If you have issues compiling the source code or running it, issues in github is the right place. If the game has bugs (like crashes that happen with the regular version from steam), the bug reports in the forum is the right place. Simply as that :)

**Comment by Morketh** [comment]
Off Topic
