### ISSUE TITLE
Player Collision is terrible

### ISSUE THREAD

**Issue by Trojaner** [KeenSoftwareHouse/SpaceEngineers#547]
Today I decided to play a bit Space Engineers. This is what happened in 2 hours of multiplayer:

I was drilling a hole on the earth surface and suddenly I started to fall trough the planet. 
Beside that, walking on blocks is very glitchy. Like really really glitchy. I died multiple times just by walking on my ship which wasn't even moving  (I dont want to know what happens on a flying ship...). Same for stations. I just get pushed back random and loose health. Mostly this happens when walking up. Also, I fell often trough incompleted blocks and was stuck in the block below it.

These bugs make the whole game unplayable :unamused:

**Comment by Jimmacle** [comment]
You're not saying anything new. Keen is working on making everything smooth in addition to adding new features which is a pretty difficult task.

**Comment by andrewfenn** [comment]
Could you upload a small demo save game with instructions on how to reproduce the issue?

**Comment by Trojaner25** [comment]
This didn't happen on a local server, nor on a server which I own. So I can't provide any demos
