### ISSUE TITLE
[Request] If a server returns its version as 00_000_000, join anyway.

### ISSUE THREAD

**Issue by aaronfranke** [KeenSoftwareHouse/SpaceEngineers#558]
For some reason, sometimes the server's game version reports incorrectly as 00_000_000. I understand why this check exists, but if this version is returned, then obviously the check failed. Instead of being unable to join the game, it'd make more sense to just join anyway. The person joining probably knows that they're joining a compatible server, as usually it's a friend's server.

**Comment by N3X15** [comment]
Wouldn't it be more productive to fix the issue where it returns 00_000_000?

**Comment by aaronfranke** [comment]
Probably, but seeing as how it hasn't been fixed for years, Keen must not be caring about that bug, or don't know how to fix it.

**Comment by N3X15** [comment]
Are there reproduction steps for getting that version?  I'd be happy to make a PR (although the version of SE in the repo is 22 days old now)

**Comment by aaronfranke** [comment]
I have no idea how to reproduce, it just seems to happen.

**Comment by mexmer** [comment]
if server that is returning version 000_000_000 is using SESE, you might ask SESE authors instead, i don't believe there is issue with server itself. At least i never seen this issue, i'm running vanilla server since 1.070 or so.

**Comment by N3X15** [comment]
SECE won't even list standard SE servers, and vice versa.  That's by design.

**Comment by aaronfranke** [comment]
I'm not using SESE and I don't even know what that is.

**Comment by aaronfranke** [comment]
Closing since SE no longer uses GitHub.
