### ISSUE TITLE
SharpDX.XAudio Creation Failure (XAUDIO2_E_XAPO_CREATION_FAILED)

### ISSUE THREAD

**Issue by CallumCarmicheal** [KeenSoftwareHouse/SpaceEngineers#563]
This error is currently only on the develop branch in steam.

The developer [Hellwiss_cz](http://steamcommunity.com/profiles/76561197962426033) said this due to new realistic sound option. 

and advised to upload the log so developers could look into this matter: [SpaceEngineers Log](https://github.com/KeenSoftwareHouse/SpaceEngineers/files/491962/SpaceEngineers.txt)

**Comment by lord-devious** [comment]
Go to the bug report forums. These issues are for the contributors, not Keen.
http://forums.keenswh.com/forums/bug-reports.326950/
