### ISSUE TITLE
Can we get an update on the repo? 

### ISSUE THREAD

**Issue by Pingger** [KeenSoftwareHouse/SpaceEngineers#588]
Hi,
I'm sitting here trying to figure out how accomplish a few things using IngameProgramming, but because there where 2 huge ModApi Changes since the last Repository Sync it is quiet hard to find what I'm looking for. So please update the repository finally ... Last update was more than 9 months ago!

Greetings

**Comment by spacebuilder2020** [comment]
See https://github.com/KeenSoftwareHouse/SpaceEngineers/issues/584#issuecomment-323160847
While I think it would be nice if they would update the source here eventually just to bring it up to date with the master but it does not seem like that is going to happen any time soon if at all.

As for getting help with in game scripting, You probably don't need the repo updated to do that.

You can just link visual studio to the dlls in your steam installation and use visual studio's code completion to help you.  I think the code has documentation annotations in the dlls.

If you are unable to get visual studio working or have other questions related to the scripting, I would suggest asking on the InGameProgramming channel on Keen's Discord.

**Comment by Pingger** [comment]
Thanks.
For some reason this issue isn't displayed in the issue list for me ...
Regarding VS, currently I do reference the dlls, but only very few methods and attributes have documentation attached to it. Which isn't neccessarily bad, but in some cases necessary ... 
In my particular case I'd like to know what happens, when I move an Item in the same inventory onto different item, and if it stacks or just swaps, but both InventoryMove Methods are undocumented ...

**Comment by spacebuilder2020** [comment]
Closed issues do not show up by default.  You have to filter to see closed issues.

But just ask around on discord.
