### ISSUE TITLE
Server Browser uses a lot of bandwidth

### ISSUE THREAD

**Issue by Trojaner25** [KeenSoftwareHouse/SpaceEngineers#590]
When I refresh the ingame server browser, almost all available internet bandwidth is used.
For example, I get about 3000ms lag on a VoIP application when I refresh the list (also refreshing takes a lot of time, like a couple of minutes)

**Comment by Pingger** [comment]
you might want to check your steam settings.
In Steam Settings > In-Game > "In-Game server browser: Max pings/minute" (bottom) 
Lower the value from your currently set value.

**Comment by Trojaner25** [comment]
Well it was already at 500 which is the second lowest value.
I set it to 250 but I dont think its going to change much

Since this is Steam related and this repo is dead anyway, I will close this
