### ISSUE TITLE
Since the Open Source release of Space Engineers, i'm not able to...

### ISSUE THREAD

**Issue by labo-css** [KeenSoftwareHouse/SpaceEngineers#6]
find a better game than this. You are really awesome KSH. Keep doing what you do. The community will always stay with you :+1:

**Comment by mccorkle** [comment]
I had to read this twice to get what you were saying :-) 

And agreed.  Keen is changing the AAA game development world in a good way.

**Comment by labo-css** [comment]
Sorry, i'm french.

**Comment by mccorkle** [comment]
Not at all, it is clever. It just took me reading the subject and body
together.

**Comment by zrisher** [comment]
:+1:

**Comment by vasili111** [comment]
You are gues one of the best developers that I have heard about.

**Comment by Spartan322** [comment]
:+1: :100:

**Comment by Silom** [comment]
@labo-css well, its not really AAA. Anyway I support this decision they made and probably even start of modding again :+1: :)

**Comment by jbaiera** [comment]
Guys, we all agree with this sentiment, but this is an issue tracking system - not a forum.

**Comment by Spartan322** [comment]
@jbaiera I agree with this guy, but yes you are right, please close this issue.
