### ISSUE TITLE
Steam Proton RX 6800 XT Grass Density Bug Causes full system lockup

### ISSUE THREAD

**Issue by panmarco83** [KeenSoftwareHouse/SpaceEngineers#609]
Ubuntu 20.04.2
LLVM 12.0.0-3ubuntu1~20.04.3 (don't know why it's stated as Ubuntu 20.04.3 and not .2)
Mesa 21.3.0-devel
XFX RX 6800 XT
Steam Proton 6.3-5, experimental and 5.13-6 are tested.

1. Start the game.
2. When in main menu, have grass density anywhere higher than 0.
3. Start new game / Load saved game (don't know about multiplayer, but I suspect the same there as well)
After a few moments of loading, screen(s) will freeze and then the screen(s) will go black for a moment
then come back to desktop possibly with mouse still movable if it was visible.
At this point, no alt+tab, alt+f4 or anything other than ctrl+alt+f1(2,3,4..) will work.
In console, you can try to kill space engineers but it will not help.
I have not tried restarting LightDM/GDM/KDM/(whatever login manager anyone else has) to see if it helps.
This makes me think there is something in the shader(?) that governs the density of the grass on planets might be at fault here ?

**Comment by Krienas** [comment]
you should report these https://support.keenswh.com/spaceengineers

**Comment by panmarco83** [comment]
Damn, I was hoping it would be enough to report it here.
I'm of the paranoid sort so creating onetime-use accounts on the net is not something I feel comfortable doing.
Should I just close this issue in this case ?

**Comment by Krienas** [comment]
This repo is dead for years. I am the same player as you. I would close this issue, but it is up to you to decide what do you want to do. I simply shared info about correct place to do this. Btw you can use google for authentication there.

**Comment by panmarco83** [comment]
Well, anyway, I'll just close this for now and hope someone sees it at some point.
