### ISSUE TITLE
Issues with starting game in Windowed Mode

### ISSUE THREAD

**Issue by brucem91** [KeenSoftwareHouse/SpaceEngineers#71]
Hello All,

I have noticed 3 issues with Windowed Mode. I normally play in Windowed Mode with a resolution of 1600x900.

Issue 1: On startup, SE remembers to set itself to Windowed mode, but does not set the resolution to what was previously set. 

Issue 2: Additionally, SE will set the window size to the highest supported, however it will only render at whatever was set in the video settings.

Issue 3 (Really 2.1): If you now go to the video settings, it will read as your last supported resolution, however you will be rendering at whatever is in your config file. 

The easiest way to reproduce this is to set SE to Windowed Mode and at the lowest possible setting. After you save this config, if you restart SE you will notice SE taking up most of your screen, but drawing at a very low resolution.

After digging in the source code, it looks like SE is running the following logic:

1. Check if requested DisplaySetting (width, height, refresh rate) exists in list of SupportedDisplayModes. If so, we return with this value.

2. If not, we setup a fallback mode using the last in the list of supported display modes

3. Otherwise (and I'm skipping some logic here), we create a screen mode with fallback settings (800x600).

The easiest way I am finding to fix this is to force modeExists = true either by removing the foreach loop in vrage.render\myrender-device.CreateDevice() or simply setting modeExists = true after the end of the loop. This solves both issues 1 and 2, however it then bypasses the whole logic of checking if we have a supported resolution.

After MyRender-Device.CreateDevice, if we don't use the easy fix above, it then returns the last supported display mode from the list. It is then after this code that creates the window using this setting, but uses our preferred render settings for the actual rendering. 

Any ideas?

**Comment by THDigi** [comment]
I frequently play on windowed on 1600x900 while having 1920x1080 desktop resolution and I don't have any of those issues, even with the reproduction steps.

Any extra details would probably help devs to replicate the issue... OS, desktop resolution, supported monitor frequency, GPU model and if you have more GPUs (integrated or crossfire/SLI).

And are you running any frequency forcer programs ? Maybe your GPU's control panel or something.

Game's video settings might also help.

**Comment by brucem91** [comment]
Sure, thanks for the response.

OS: Windows 8.1 Pro 64-bit (6.3, Build 9600)
CPU: AMD FX(tm)-6300 Six-Core Process @ 3.5 GHz
RAM: 8GB DDR3
GPU: NVIDIA GeForce GTX 660 2GB (approx 2 extra GB shared from system memory) (only 1 GPU, no SLI or Crossfire)

My primary display outside of games runs at 1920x1080 (32 bit) at 60Hz. According to both Windows and the NVIDIA Control Panel, my primary monitor only supports 60Hz. I'm basically running with the drivers i update every few months, I don't otherwise install any other programs. 

In game I normally run:
Video Mode: 1600x900
Window Mode: WINDOW
Vertical Sync: NO
Hardware Cursor: YES
Render Quality: NORMAL
Render Interpolation: YES
Enable Damage Effects: YES
Field of View: 60.0 (Default)

I also just figured out why my resolution wasn't being found on startup. Somehow SE was setting the refresh rate to 75 in the config file, where as all list of supported display types would all be 60 Hz.Manually setting this to 60 Hz does seem to fix it.
