### ISSUE TITLE
SpaceEngineers project won't load

### ISSUE THREAD

**Issue by aequis** [KeenSoftwareHouse/SpaceEngineers#80]
As in the title, the SpaceEngineers project won't load. All the others work fine. It just says "load failed" next to the name in the Solution Explorer and gives me the following error:

\git\SpaceEngineers\Sources\SpaceEngineers\SpaceEngineers.csproj : error  : The expression "[System.IO.Directory]::GetDirectories(c:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Content)" cannot be evaluated. Could not find a part of the path 'c:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Content'.  \git\SpaceEngineers\Sources\SpaceEngineers\SpaceEngineers.csproj

Btw, my Steam folder is on another drive and not in the default location, so obviously it won't find the game's content folder there.

**Comment by mexmer** [comment]
http://forum.keenswh.com/threads/source-code-compilation-requirements-and-stuff.7360002/
https://github.com/KeenSoftwareHouse/SpaceEngineers/wiki/Initial-setup#setting-path-to-the-games-content

**Comment by aequis** [comment]
The one time I skip the readme. *facepalm* Sorry about that, but many thanks.
