### ISSUE TITLE
Shouldn't MyTerminalControlCheckBox also inherit from MyTerminalValueControl?

### ISSUE THREAD

**Issue by lord-devious** [KeenSoftwareHouse/SpaceEngineers#81]
[This is a question for the devs]

So that any checkboxes in the UI get their terminal properties for ingame scripting, like the slider and color controls does?

**Comment by mexmer** [comment]
I would extend that to On/Off switches ... since they are only true/false also.
I'm not sure how that will interfere with existing exposed fields tho'

**Comment by lord-devious** [comment]
Agreed. I'd say all controls should, if possible.

**Comment by lord-devious** [comment]
I wonder just how many times I'm gonna do that.

**Comment by mexmer** [comment]
i think, we can close this issue now, since #207 is merged

**Comment by lord-devious** [comment]
True.
