### ISSUE TITLE
Add an asteroid using an existing MyVoxelMapStorageDefinition.

### ISSUE THREAD

**Issue by midspace** [KeenSoftwareHouse/SpaceEngineers#89]
Currently, calling ...
Sandbox.Definitions.MyDefinitionManager.GetVoxelMapStorageDefinitions()
will return a list of ...
public ListReader<MyVoxelMapStorageDefinition>

We need a method on IMyVoxelMaps, that will allow us to specify a MyVoxelMapStorageDefinition to create a voxel map in game.
CreateVoxelMap(string id, Vector3D position);

or....

allow us clone the Storage on the MyVoxelMapStorageDefinition, to use in the existing CreateVoxelMap() method.

**Comment by fabricator77** [comment]
I have update the branch with two extra commits, should fix sandbox issues, but I'm not able to test it. I've not called it CreateVoxelMap as that creates confusion with the existing function that requires more input data. The existing CreateVoxelMap is more a SaveVoxelMap to be honest.

**Comment by midspace** [comment]
Has been added to code now.
