### ISSUE TITLE
MyPowerReceiver accessibility

### ISSUE THREAD

**Issue by mexmer** [KeenSoftwareHouse/SpaceEngineers#97]
i would like to be able to access PowerConsumer with ingame api, so we can write power management scripts without need parsing data from detailed info (which is also incomplete)

values what i think we need
IsPowered
IsAdaptible
MaxRequiredInput
RequiredInput
CurrentInput

**Comment by MMaster** [comment]
This is definitely needed. I was thinking about adding it to battery interface in PR #19 but figured that it would be much better to do it more generically.

**Comment by mexmer** [comment]
rough sketch here
https://github.com/mexmer/SpaceEngineers/tree/powerfields-redo
after seeing what ondrej has done with IMyPowerProducer i redone all code and deleted old code branch
interface name IMyPowerConsumerBlock is intentional to differentiate from IMyPowerReceiver interface ... name is subject to change

**Comment by mexmer** [comment]
closing due code changes
