### ISSUE TITLE
DS On/Off switches text and values

### ISSUE THREAD

**Issue by mexmer** [KeenSoftwareHouse/SpaceEngineers#98]
can any of devs please shed some light to this part of code
if i comment out that "TEMPORAL HACK" line, it solves problem with some of my script on DS

Sources\Sandbox.Game\Game\Screens\Terminal\Controls\MyTerminalControlOnOffSwitch.cs, line 49

```C#
    public MyTerminalControlOnOffSwitch(string id, MyStringId title, MyStringId tooltip = default(MyStringId), MyStringId? on = null, MyStringId? off = null)
        : base(id)
    {
        if (MySandboxGame.IsDedicated) return; // Temporal hack 

        Title = title;
        OnText = on ?? MySpaceTexts.SwitchText_On;
        OffText = off ?? MySpaceTexts.SwitchText_Off;
        Tooltip = tooltip;
    }
```

this line of code prevents DS from loading on/off switches decription, and also on/off text value, which results in returning empty string, therefore you cannot check if something is switched On or Off, this is problem, since not all On/Off switches have coresponding Property exposed on interface.

**Comment by OndrejPetrzilka** [comment]
It was there because controls were created in constructor in past (not in CreateGui). This was workaround to prevent server crash, it should have been removed when writing CreateGui()

Fixed by 2073ef1743fca874b9ac748c0ee07677e151b208
